"""empty message

Revision ID: df847cdf511a
Revises: d949641b60c8
Create Date: 2020-11-18 16:17:04.021262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df847cdf511a'
down_revision = 'd949641b60c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen_user', sa.DateTime(), nullable=False))
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.VARCHAR(length=60), nullable=True))
        batch_op.drop_column('last_seen_user')

    # ### end Alembic commands ###
